/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Model.glb 
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from "gsap"
import { useFrame } from 'react-three-fiber';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Cube(props) {
  const { nodes, materials } = useGLTF('./models/model.glb')
  const ref = useRef();

  useEffect(() => {
    if (ref.current) {
      // Promjena boje svih mesh objekata
      ref.current.children.forEach((child) => {
        if (child.material) {
          child.material.color.set('#44ddc0'); // Postavljanje boje na ljubičastu
        }
      });
    }
  }, []);
//   const tl = useRef();

//   const scroll = useScroll()

//   useFrame(() => {
//     tl.current.seek(scroll.offset * tl.current.duration())
//   })

//   useLayoutEffect(() => {
//     tl.current = gsap.timeline()

//     //VERTICAL ANIMATION
//     tl.current.to(
//         ref.current.position,
//         {
//             duration: 2,
//             y:-FLOOR_HEIGHT * (NB_FLOORS -1),
//         },
//         0
//     )
//   },[])
// Use useFrame to rotate the object in each frame
useFrame((state, delta) => {
    // Rotate the object about the Y-axis
    ref.current.rotation.y += delta * 0.2; // Adjust the rotation speed as needed
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.007']}  position={[-0.354, 4.212, 0.04]} rotation={[0.227, -0.887, -0.037]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} position={[-0.369, 5.248, -0.884]} rotation={[0.227, -0.887, -0.037]} scale={1.419} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.007']} position={[-1.344, 4.906, 0.067]} rotation={[0.227, -0.887, -0.037]} scale={0.51} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.007']} position={[1.34, 3.381, -1.846]} rotation={[0.093, -0.866, 0.071]} scale={0.853} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.007']} position={[0.104, 2.178, -0.743]} rotation={[0, -0.869, -0.104]} scale={1.232} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.007']} position={[0.669, 2.348, -0.447]} rotation={[0, -0.869, -0.104]} scale={1.159} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.007']} position={[1.317, 3.16, -0.329]} rotation={[0.073, -0.873, -0.157]} scale={1.159} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.007']} position={[0.211, 0.333, -1.078]} rotation={[-0.303, -0.824, -0.332]} scale={0.992} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.007']} position={[-0.601, 2.884, -0.997]} rotation={[0.2, -0.865, 0.154]} scale={0.992} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.007']} position={[0.717, 3.71, -2.612]} rotation={[0.093, -0.866, 0.071]} scale={0.345} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.007']} position={[0.74, 3.161, -2.586]} rotation={[0.093, -0.866, 0.071]} scale={0.232} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.007']} position={[0.741, 4.533, -1.936]} rotation={[0.209, -0.886, -0.051]} scale={0.232} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-0.851, 4.444, -1.986]} rotation={[0.135, 0, 0]} scale={0.232} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.007']} position={[1.333, 4.509, -1.807]} rotation={[0.209, -0.886, -0.051]} scale={0.343} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.007']} position={[0.717, 3.71, -2.612]} rotation={[0.093, -0.866, 0.071]} scale={0.345} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.007']} position={[0.01, 3.88, -0.94]} rotation={[0.2, -0.892, -0.055]} scale={1.133} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.007']} position={[1.382, 2.143, -1.384]} rotation={[1.392, -0.354, 0.816]} scale={1.159} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.007']} position={[-0.561, 2.156, -0.237]} rotation={[0, -0.869, 0]} scale={0.63} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.007']} position={[-0.01, 6.021, -0.976]} rotation={[0.227, -0.887, -0.037]} scale={0.745} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.007']} position={[0.243, 6.721, -1.023]} rotation={[0.143, -0.031, -0.209]} scale={0.328} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.007']} position={[1.42, 3.175, 0.746]} rotation={[0.073, -0.873, -0.157]} scale={0.518} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.007']} position={[-1.519, 4.699, 0.771]} rotation={[0.227, -0.887, -0.037]} scale={0.352} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.007']} position={[-0.28, 5.565, -2.511]} rotation={[0.213, -0.829, 0.353]} scale={1.03} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.007']} position={[0.906, -3.466, -0.374]} rotation={[-2.415, -0.15, -0.647]} scale={0.641} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.007']} position={[2.863, -2.915, -1.476]} rotation={[-2.729, 0.044, 0.225]} scale={0.775} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.007']} position={[1.429, -1.233, -1.437]} rotation={[-2.493, 0.575, 0.545]} scale={[0.779, 0.701, 0.74]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.007']} position={[1.461, -1.676, -0.684]} rotation={[Math.PI, 0.333, 0.482]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.007']} position={[1.429, -1.233, -1.437]} rotation={[-2.493, 0.575, 0.545]} scale={[0.779, 0.701, 0.74]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.007']} position={[1.963, -0.943, -1.331]} rotation={[-2.493, 0.575, 0.545]} scale={[0.664, 0.598, 0.631]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.007']} position={[2.028, -1.046, 0.051]} rotation={[2.992, 0.309, 0.388]} scale={1.054} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.007']} position={[2.702, -2.202, -0.288]} rotation={[-2.641, 0.5, 0.213]} scale={0.56} />
    </group>
  )
}

useGLTF.preload('./models/model.glb')
